package com.jtrace.zeus.jvm.parameters.parameters;

/**
 * @author xule05
 * @date 2020/1/27 下午8:45
 */

public class JvmParametersInfo {
    /**
     * 所有参数
     */
    public static final String infos=
            "-agentlib:libname[=options]\n" +
            "-agentpath:pathname[=options]\n" +
            "-client\n" +
            "-Dproperty=value\n" +
            "-disableassertions[:[packagename]...|:classname]\n" +
            "-da[:[packagename]...|:classname]\n" +
            "-disablesystemassertions\n" +
            "-dsa\n" +
            "-enableassertions[:[packagename]...|:classname]\n" +
            "-ea[:[packagename]...|:classname]\n" +
            "-enablesystemassertions\n" +
            "-esa\n" +
            "-help\n" +
            "-?\n" +
            "-jar filename\n" +
            "-javaagent:jarpath[=options]\n" +
            "-jre-restrict-search\n" +
            "-no-jre-restrict-search\n" +
            "-server\n" +
            "-showversion\n" +
            "-splash:imgname\n" +
            "-verbose:class\n" +
            "-verbose:gc\n" +
            "-verbose:jni\n" +
            "-version\n" +
            "-version:release\n" +
            "-X\n" +
            "-Xbatch\n" +
            "-Xbootclasspath:path\n" +
            "-Xbootclasspath/a:path\n" +
            "-Xbootclasspath/p:path\n" +
            "-Xcheck:jni\n" +
            "-Xcomp\n" +
            "-Xdebug\n" +
            "-Xdiag\n" +
            "-Xfuture\n" +
            "-Xint\n" +
            "-Xinternalversion\n" +
            "-Xloggc:filename\n" +
            "-Xmaxjitcodesize=size\n" +
            "-Xmixed\n" +
            "-Xmssize\n" +
            "-Xmxsize\n" +
            "-Xnoclassgc\n" +
            "-Xprof\n" +
            "-Xrs\n" +
            "-Xshare:mode\n" +
            "-XshowSettings:category\n" +
            "-Xsssize\n" +
            "-Xverify:mode\n" +
            "-XX:+CheckEndorsedAndExtDirs\n" +
            "-XX:+DisableAttachMechanism\n" +
            "-XX:ErrorFile=filename\n" +
            "-XX:+FailOverToOldVerifier\n" +
            "-XX:+FlightRecorder\n" +
            "-XX:-FlightRecorder\n" +
            "-XX:FlightRecorderOptions=parameter=value\n" +
            "-XX:LargePageSizeInBytes=size\n" +
            "-XX:MaxDirectMemorySize=size\n" +
            "-XX:NativeMemoryTracking=mode\n" +
            "-XX:ObjectAlignmentInBytes=alignment\n" +
            "-XX:OnError=string\n" +
            "-XX:OnOutOfMemoryError=string\n" +
            "-XX:+PerfDataSaveToFile\n" +
            "-XX:+PrintCommandLineFlags\n" +
            "-XX:+PrintNMTStatistics\n" +
            "-XX:+RelaxAccessControlCheck\n" +
            "-XX:+ResourceManagement\n" +
            "-XX:ResourceManagementSampleInterval=value (milliseconds)\n" +
            "-XX:SharedArchiveFile=path\n" +
            "-XX:SharedClassListFile=file_name\n" +
            "-XX:+ShowMessageBoxOnError\n" +
            "-XX:StartFlightRecording=parameter=value\n" +
            "-XX:ThreadStackSize=size\n" +
            "-XX:+TraceClassLoading\n" +
            "-XX:+TraceClassLoadingPreorder\n" +
            "-XX:+TraceClassResolution\n" +
            "-XX:+TraceClassUnloading\n" +
            "-XX:+TraceLoaderConstraints\n" +
            "-XX:+UnlockCommercialFeatures\n" +
            "-XX:+UseAppCDS\n" +
            "-XX:-UseBiasedLocking\n" +
            "-XX:-UseCompressedOops\n" +
            "-XX:+UseLargePages\n" +
            "-XX:+UseMembar\n" +
            "-XX:+UsePerfData\n" +
            "-XX:+AllowUserSignalHandlers\n" +
            "-XX:+AggressiveOpts\n" +
            "-XX:AllocateInstancePrefetchLines=lines\n" +
            "-XX:AllocatePrefetchDistance=size\n" +
            "-XX:AllocatePrefetchInstr=instruction\n" +
            "-XX:AllocatePrefetchLines=lines\n" +
            "-XX:AllocatePrefetchStepSize=size\n" +
            "-XX:AllocatePrefetchStyle=style\n" +
            "-XX:+BackgroundCompilation\n" +
            "-XX:CICompilerCount=threads\n" +
            "-XX:CodeCacheMinimumFreeSpace=size\n" +
            "-XX:CompileCommand=command,method[,option]\n" +
            "-XX:CompileCommandFile=filename\n" +
            "-XX:CompileOnly=methods\n" +
            "-XX:CompileThreshold=invocations\n" +
            "-XX:+DoEscapeAnalysis\n" +
            "-XX:InitialCodeCacheSize=size\n" +
            "-XX:+Inline\n" +
            "-XX:InlineSmallCode=size\n" +
            "-XX:+LogCompilation\n" +
            "-XX:MaxInlineSize=size\n" +
            "-XX:MaxNodeLimit=nodes\n" +
            "-XX:MaxTrivialSize=size\n" +
            "-XX:+OptimizeStringConcat\n" +
            "-XX:+PrintAssembly\n" +
            "-XX:+PrintCompilation\n" +
            "-XX:+PrintInlining\n" +
            "-XX:ReservedCodeCacheSize=size\n" +
            "-XX:RTMAbortRatio=abort_ratio\n" +
            "-XX:RTMRetryCount=number_of_retries\n" +
            "-XX:-TieredCompilation\n" +
            "-XX:+UseAES\n" +
            "-XX:+UseAESIntrinsics\n" +
            "-XX:+UseCodeCacheFlushing\n" +
            "-XX:+UseCondCardMark\n" +
            "-XX:+UseRTMDeopt\n" +
            "-XX:+UseRTMLocking\n" +
            "-XX:+UseSHA\n" +
            "-XX:+UseSHA1Intrinsics\n" +
            "-XX:+UseSHA256Intrinsics\n" +
            "-XX:+UseSHA512Intrinsics\n" +
            "-XX:+UseSuperWord\n" +
            "-XX:+HeapDumpOnOutOfMemoryError\n" +
            "-XX:HeapDumpPath=path\n" +
            "-XX:LogFile=path\n" +
            "-XX:+PrintClassHistogram\n" +
            "-XX:+PrintConcurrentLocks\n" +
            "-XX:+UnlockDiagnosticVMOptions\n" +
            "-XX:ActiveProcessorCount=x\n" +
            "-XX:+AggressiveHeap\n" +
            "-XX:+AlwaysPreTouch\n" +
            "-XX:+CMSClassUnloadingEnabled\n" +
            "-XX:CMSExpAvgFactor=percent\n" +
            "-XX:CMSInitiatingOccupancyFraction=percent\n" +
            "-XX:+CMSScavengeBeforeRemark\n" +
            "-XX:CMSTriggerRatio=percent\n" +
            "-XX:ConcGCThreads=threads\n" +
            "-XX:+DisableExplicitGC\n" +
            "-XX:+ExplicitGCInvokesConcurrent\n" +
            "-XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses\n" +
            "-XX:G1HeapRegionSize=size\n" +
            "-XX:+G1PrintHeapRegions\n" +
            "-XX:G1ReservePercent=percent\n" +
            "-XX:InitialHeapSize=size\n" +
            "-XX:InitialRAMPercentage=percent\n" +
            "-XX:InitialSurvivorRatio=ratio\n" +
            "-XX:InitiatingHeapOccupancyPercent=percent\n" +
            "-XX:MaxGCPauseMillis=time\n" +
            "-XX:MaxHeapSize=size\n" +
            "-XX:MaxHeapFreeRatio=percent\n" +
            "-XX:MaxMetaspaceSize=size\n" +
            "-XX:MaxRAMPercentage=percent\n" +
            "-XX:MaxNewSize=size\n" +
            "-XX:MaxTenuringThreshold=threshold\n" +
            "-XX:MetaspaceSize=size\n" +
            "-XX:MinHeapFreeRatio=percent\n" +
            "-XX:MinRAMPercentage=percent\n" +
            "-XX:NewRatio=ratio\n" +
            "-XX:NewSize=size\n" +
            "-XX:ParallelGCThreads=threads\n" +
            "-XX:+ParallelRefProcEnabled\n" +
            "-XX:+PrintAdaptiveSizePolicy\n" +
            "-XX:+PrintGC\n" +
            "-XX:+PrintGCApplicationConcurrentTime\n" +
            "-XX:+PrintGCApplicationStoppedTime\n" +
            "-XX:+PrintGCDateStamps\n" +
            "-XX:+PrintGCDetails\n" +
            "-XX:+PrintGCTaskTimeStamps\n" +
            "-XX:+PrintGCTimeStamps\n" +
            "-XX:+PrintStringDeduplicationStatistics\n" +
            "-XX:+PrintTenuringDistribution\n" +
            "-XX:+ScavengeBeforeFullGC\n" +
            "-XX:SoftRefLRUPolicyMSPerMB=time\n" +
            "-XX:StringDeduplicationAgeThreshold=threshold\n" +
            "-XX:SurvivorRatio=ratio\n" +
            "-XX:TargetSurvivorRatio=percent\n" +
            "-XX:TLABSize=size\n" +
            "-XX:+UseAdaptiveSizePolicy\n" +
            "-XX:+UseCMSInitiatingOccupancyOnly\n" +
            "-XX:+UseConcMarkSweepGC\n" +
            "-XX:+UseG1GC\n" +
            "-XX:+UseGCOverheadLimit\n" +
            "-XX:+UseNUMA\n" +
            "-XX:+UseParallelGC\n" +
            "-XX:+UseParallelOldGC\n" +
            "-XX:+UseParNewGC\n" +
            "-XX:+UseSerialGC\n" +
            "-XX:+UseStringDeduplication\n" +
            "-XX:+UseTLAB\n" +
            "-Xincgc\n" +
            "-Xrunlibname\n" +
            "-XX:CMSIncrementalDutyCycle=percent\n" +
            "-XX:CMSIncrementalDutyCycleMin=percent\n" +
            "-XX:+CMSIncrementalMode\n" +
            "-XX:CMSIncrementalOffset=percent\n" +
            "-XX:+CMSIncrementalPacing\n" +
            "-XX:CMSIncrementalSafetyFactor=percent\n" +
            "-XX:CMSInitiatingPermOccupancyFraction=percent\n" +
            "-XX:MaxPermSize=size\n" +
            "-XX:PermSize=size\n" +
            "-XX:+UseSplitVerifier\n" +
            "-XX:+UseStringCache";
}
